spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/testdb
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password:
#  main:
#    web-application-type: none
